branches:
  only:
  - master
dist: xenial
sudo: required
language: minimal
env:
  - ARCH=x86_64
  - ARCH=x86
install:
  - sudo .travis/install
script: |
  . .travis/config
  sudo chroot $NEWROOT su -l $USER sh -c "cd $CLONE_DIR; make ARCH=$ARCH; make ARCH=$ARCH check"
notifications:
  email: false
